### PR TITLE
added gaussian elimination

### PR DESCRIPTION
**Pull request by lucaferranti**
```julia
julia> A = @MMatrix[4..6 -1..1 -1..1 -1..1;-1..1 -6.. -4 -1..1 -1..1;-1..1 -1..1 9..11 -1..1;-1..1 -1..1 -1..1 -11.. -9]
4×4 MMatrix{4, 4, Interval{Float64}, 16} with indices SOneTo(4)×SOneTo(4):
  [4, 6]   [-1, 1]  [-1, 1]    [-1, 1]
 [-1, 1]  [-6, -4]  [-1, 1]    [-1, 1]
 [-1, 1]   [-1, 1]  [9, 11]    [-1, 1]
 [-1, 1]   [-1, 1]  [-1, 1]  [-11, -9]

julia> b = @MVector [-2..4, 1..8, -4..10, 2..12]
4-element MVector{4, Interval{Float64}} with indices SOneTo(4):
  [-2, 4]
   [1, 8]
 [-4, 10]
  [2, 12]

julia> ge = GaussElimination()
GaussElimination linear solver

julia> @btime solve($A, $b, $ge)
  4.543 μs (167 allocations: 7.08 KiB)
4-element MVector{4, Interval{Float64}} with indices SOneTo(4):
 [-2.60001, 3.10001]
 [-3.90001, 1.50001]
 [-1.43001, 2.15001]
 [-2.35001, 0.600001]
```

the results are in accordance with the experiments in the thesis, but I think from efficiency perspective there's much room for improvement.

### CODE REVIEW

**Comment by lucaferranti** [comment]
@mforets I cannot add you as reviewer apparently, so here's an old fashioned manual ping :)

**Comment by mforets** [comment]
Update based on the meeting of 29th june:

```julia
function rref(A)
    A1 = copy(A)
    return rref!(A1)
end

@inline function _findmax_mig(v::AbstractVector{N}) where N
    migmax = N(-Inf)
    local kmax
    @inbounds for k in eachindex(v)
        migi = mig(v[k])
        if migi > migmax
            migmax = migi
            kmax = k
        end
    end
    return kmax
end

@inline function _swap!(A, k, kp)
    @inbounds for i = 1:size(A, 2)
        tmp = A[k, i]
        A[k, i] = A[kp, i]
        A[kp, i] = tmp
    end
end

@inline function _scale!(A, k)
    @inbounds begin
        Akkinv = inv(A[k, k])
        for i = k+1:size(A, 1)
            A[i, k] *= Akkinv
        end
    end
end

@inline function _elimination!(A, k)
    m, n = size(A)
    @inbounds begin
        for j = k+1:n
            for i = k+1:m
                A[i, j] -= A[i, k] * A[k, j]
            end
        end

        for i = k+1:m
            A[i, k] = zero(eltype(A))
        end
    end
end

function rref!(A)
    m, n = size(A)
    minmn = min(m,n)

    @inbounds begin        
        for k = 1:minmn

            # find row with maximum mignitude
            kp = k
            if k < m
                kp = _findmax_mig(view(A, k:m, k))
                kp += k-1
            end

            iszero(A[kp, k]) && throw(ArgumentError("Could not find a pivot with non-zero mignitude in column $k, matrix is possibly non regular."))

            # Interchange
            if k != kp
                _swap!(A, k, kp)
            end

            # Scale first column
            _scale!(A, k)
            
            # Update the rest
            _elimination!(A, k)
        end
    end
    return A
end
```

**Comment by lucaferranti** [comment]
@mforets I have refactored the `rref` function, now is waay more readable. Here are the benchmarks on my machine

### Current commit
```julia
julia> A = [4..6 -1..1 -1..1 -1..1;-1..1 -6.. -4 -1..1 -1..1;-1..1 -1..1 9..11 -1..1;-1..1 -1..1 -1..1 -11.. -9]

julia> @benchmark rref($A)
BenchmarkTools.Trial: 
  memory estimate:  592 bytes
  allocs estimate:  17
  --------------
  minimum time:     1.230 μs (0.00% GC)
  median time:      1.430 μs (0.00% GC)
  mean time:        1.563 μs (1.62% GC)
  maximum time:     255.070 μs (99.09% GC)
  --------------
  samples:          10000
  evals/sample:     10
```

### Previous commit
```julia
julia> @benchmark rref($A)
BenchmarkTools.Trial: 
  memory estimate:  592 bytes
  allocs estimate:  17
  --------------
  minimum time:     970.000 ns (0.00% GC)
  median time:      1.170 μs (0.00% GC)
  mean time:        1.262 μs (1.29% GC)
  maximum time:     165.420 μs (98.80% GC)
  --------------
  samples:          10000
  evals/sample:     10
```

**Review by mforets — APPROVED** [review]

**Comment by lucaferranti** [comment]
Tried with a random 50x50 matrix.

### Current commit
```julia
julia> @benchmark rref($A)
BenchmarkTools.Trial: 
  memory estimate:  42.27 KiB
  allocs estimate:  202
  --------------
  minimum time:     1.556 ms (0.00% GC)
  median time:      1.791 ms (0.00% GC)
  mean time:        2.379 ms (0.09% GC)
  maximum time:     6.340 ms (73.85% GC)
  --------------
  samples:          2106
  evals/sample:     1
```

### Previous commit
```julia
julia> @benchmark rref($A)
BenchmarkTools.Trial: 
  memory estimate:  42.27 KiB
  allocs estimate:  202
  --------------
  minimum time:     1.578 ms (0.00% GC)
  median time:      1.815 ms (0.00% GC)
  mean time:        2.213 ms (0.19% GC)
  maximum time:     6.590 ms (73.99% GC)
  --------------
  samples:          2262
  evals/sample:     1
```

so I'd say the two approaches are equivalent, let's go with the more readable one!

**Pull request merged**
